#!/bin/bash

#PBS -N Blast
#PBS -q tiny12core
#PBS -j oe
#PBS -m abe
#PBS -M katemcd@uark.edu
#PBS -o mcdaniels_assn04.8.out
#PBS -l nodes=1:ppn=12
#PBS -l walltime=00:00:10:00

cd $PBS_O_WORKDIR

module load blast/2.6.0+

blastn -query mt.fasta -db mt.fasta -outfmt 6

blastn -outfmt 0 -dust yes -word_size 9 -reward 2 -penalty -3 -gapopen 5 -gapextend 2 -query mt.fatsa -db mt.fasta > out.blastn

blastn -outfmt 0 -dust yes -word_size 7 -reward 5 -penalty -4 -gapopen 8 -gapextend 6 -query nad4L.fasta -db mt.fasta > out.blastn

